version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorydb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: .
    container_name: formotex_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app_network
    # command: >
    #   sh -c "npx prisma migrate deploy && npm run start"

volumes:
  mysql_data:

networks:
  app_network:
